[package]
name = "raytrace"
version = "0.1.0"
edition = "2021"
authors = ["vanderh0ff"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
rand = "0.8"
